language: node_js
node_js:
- '11.0'
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --project allinone-common
  - ng build --project allinone-user
  - ng build --project allinone-admin
  - ng build --project allinone-auth
  - ng build --project allinone-corp
  - ng build --prod
addons:
  ssh_known_hosts: 
    - aio.eviannow.xyz
    - 47.47.80.166
before_install:
  - openssl aes-256-cbc -K $encrypted_376440fab1e4_key -iv $encrypted_376440fab1e4_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --rsh="ssh -p65500 -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/dist/front-end evian@aio.eviannow.xyz:/var/www/allinone/testfolder
  on:
    branch: master
